DROP DATABASE IF EXISTS AnimeTrackingSystem;
CREATE DATABASE AnimeTrackingSystem;
USE AnimeTrackingSystem;

CREATE TABLE USERS(
	usrID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usrName VARCHAR(255) NOT NULL,
    usrEmail VARCHAR(255) NOT NULL,
    usrPassword VARCHAR(255) NOT NULL,
    usrSalt VARCHAR(255) NOT NULL
);

CREATE TABLE COMMUNITY_LIST(
	cID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cName VARCHAR(255) NOT NULL,
    cType VARCHAR(255) NOT NULL,
    cAvgRating FLOAT NOT NULL,
    cGenres VARCHAR(255) NOT NULL
);

CREATE TABLE TRACKING_LIST(
	trackID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usrID INT NOT NULL,
    cID INT NOT NULL,
    startDate VARCHAR(255) NOT NULL,
    endDate VARCHAR(255) NOT NULL,
    rating DECIMAL NOT NULL,
	FOREIGN KEY (usrID) REFERENCES USERS(usrID),
    FOREIGN KEY (cID) REFERENCES COMMUNITY_LIST(cID)
);



