DROP DATABASE IF EXISTS AnimeTrackingSystem;
CREATE DATABASE AnimeTrackingSystem;
USE AnimeTrackingSystem;

CREATE TABLE USERS(
	usrID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usrName VARCHAR(255) NOT NULL,
    usrEmail VARCHAR(255) NOT NULL,
    usrPassword VARCHAR(255) NOT NULL
);

CREATE TABLE ANIME(
	animeID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usrID INT NOT NULL,
    animeName VARCHAR(255) NOT NULL,
    startDate VARCHAR(255) NOT NULL,
    endDate VARCHAR(255) NOT NULL,
    rating DECIMAL NOT NULL,
	FOREIGN KEY (usrID) REFERENCES USERS(usrID)
);
